tags:
  - "cloud-builders-community"

steps:
  - name: gcr.io/cloud-builders/docker
    id: "Build: meta cloud build triggers image"
    waitFor:
      - "-"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/meta-triggers"
      - "."
images:
  - gcr.io/$PROJECT_ID/meta-triggers
