tags:
  - "cloud-builders-community"
  - "trigger-sync"

steps:
  - name: gcr.io/cloud-builders/docker
    id: "Build: trigger-sync image"
    waitFor:
      - "-"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/trigger-sync"
      - "trigger-sync"

images:
  - gcr.io/$PROJECT_ID/trigger-sync
